apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: set-commit-status
  namespace: cicd
spec:
  params:
  - name: GIT_REPO
    type: string
  - name: REPO
    type: string
  - default: git-host-access-token
    name: GIT_TOKEN_SECRET_NAME
    type: string
  - default: token
    name: GIT_TOKEN_SECRET_KEY
    type: string
  - name: COMMIT_SHA
    type: string
  - name: DESCRIPTION
    type: string
  - default: continous-integration/tekton
    name: CONTEXT
    type: string
  - name: STATE
    type: string
  steps:
  - env:
    - name: GITHOSTACCESSTOKEN
      valueFrom:
        secretKeyRef:
          key: $(params.GIT_TOKEN_SECRET_KEY)
          name: $(params.GIT_TOKEN_SECRET_NAME)
    image: quay.io/redhat-developer/gitops-commit-status@sha256:b28e5d207f70fc37f5cbf79fabcfa2708459316d09e9def9647c06807d9464cd
    name: set-commit-status
    resources: {}
    script: gitops-commit-status --url $(params.GIT_REPO) --path $(params.REPO) --sha
      $(params.COMMIT_SHA) --context $(params.CONTEXT) --status $(params.STATE)
