apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: zb-dev-app-taxi-taxi-binding
  namespace: zb-cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/zhengbin78/image-repo
  - name: tlsVerify
    value: "true"
status: {}
